Added Custom Log class for CephFS test scripts
red-hat-storage/cephci pull request #1088
Opened 2022-01-17 08:52 UTC by udaysk23

Added Custom Log class for CephFS test scripts

Signed-off-by: udaysk23 <ukurundw@redhat.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2022-01-17 11:07 UTC, Ameenasuhani requested changes
logger = Log(__name__)
log = logger

can we have this changed as below throughout the pr
`log = Log(__name__)`

2022-01-17 14:30 UTC, Ameenasuhani reviewed
LGTM

2022-01-18 04:23 UTC, Ameenasuhani approved these changes

2022-01-18 04:46 UTC, psathyan approved these changes

2022-01-18 04:47 UTC, merged