Scaledown
red-hat-storage/cephci pull request #1194
Opened 2022-02-09 18:24 UTC by Ameenasuhani

# Description
Fixes issue: https://github.com/red-hat-storage/cephci/issues/226

Signed-off-by: Ameenasuhani <ameenasuhani@gmail.com>

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2022-02-09 19:23 UTC, Ameenasuhani commented
Added new polarion testcases:
https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574769
https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574770
https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83574771

2022-02-10 09:50 UTC, manasagowri commented on tests/ceph_ansible/shrink_daemon.py
> +        log.error("Failed during ansible playbook run\n")
Could you please add the name of the playbook which failed.

2022-02-10 09:51 UTC, manasagowri requested changes
Overall looks good. I feel more info logs can be added in shrink_daemon.py for the user to know what is being done, which would help during debugging.

2022-02-11 07:01 UTC, manasagowri reviewed
Looks good to me.

2022-02-11 07:01 UTC, manasagowri submitted a review, later dismissed

2022-02-14 05:10 UTC, sunilkumarn417 commented
@Ameenasuhani , can you please squash your commits?

2022-02-14 05:48 UTC, Ameenasuhani commented
@sunilkumarn417 Done

2022-02-15 09:55 UTC, psathyan approved these changes

2022-02-15 09:56 UTC, merged