Pick container image while switching to containerized daemons
red-hat-storage/cephci pull request #1384
Opened 2022-04-20 08:25 UTC by rahullepakshi

Pick container image for cdn and dev builds while switching to containerized daemons

Signed-off-by: rlepaksh <rlepaksh@redhat.com>

2022-04-20 09:59 UTC, rahullepakshi commented
Failure logs- http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-I5A67U/

Pass logs - 
1) Scenario where ceph_repository_type is not equal to cdn
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-86DLON/ - deployment is succesful but issue as in https://bugzilla.redhat.com/show_bug.cgi?id=2076192. 
So I reused same cluster - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-TDMHZU/

2022-04-20 16:04 UTC, sunilkumarn417 requested changes

2022-04-20 16:04 UTC, sunilkumarn417 commented on tests/ceph_ansible/switch_rpm_to_container.py
> +        file_name="/usr/share/ceph-ansible/group_vars/all.yml",
would suggest `{ansible_dir}/group_vars/all.yml` for file path.

2022-04-20 16:04 UTC, sunilkumarn417 commented on tests/ceph_ansible/switch_rpm_to_container.py
> +    if conf.get("ceph_repository_type") == "cdn":
would suggest to add this code section as separate function.

2022-04-20 16:04 UTC, sunilkumarn417 commented on tests/ceph_ansible/switch_rpm_to_container.py
> +    else:
I think we don't need `else` part, since dev conatiner image values are already set at the beginning.

2022-04-20 16:04 UTC, sunilkumarn417 commented on tests/ceph_ansible/switch_rpm_to_container.py
> +        ceph_docker_registry = sample_conf.get("ceph_docker_registry")
we could use same vars `docker_registry` `docker_image` `docker_image_tag`

2022-04-21 10:37 UTC, rahullepakshi commented
hi @sunilkumarn417 , I have addressed review comments, please review

2022-04-21 11:28 UTC, sunilkumarn417 requested changes

2022-04-21 11:28 UTC, sunilkumarn417 commented on tests/ceph_ansible/switch_rpm_to_container.py
> +    return {
We don't need to return dict here, since we are not receiving same in calling method.

`return docker_registry, docker_image, docker_image_tag`

2022-04-22 04:58 UTC, sunilkumarn417 approved these changes
LGTM

2022-04-22 04:59 UTC, merged