ceph-83573428 creating with exist names
red-hat-storage/cephci pull request #1452
Opened 2022-05-12 15:45 UTC by julpark-rh

pre-requisites:
    1. Create a random subvolume_group name that does not exist
Test operation:
    1. Try to create a subvolume on the subvolume_group name
    2. If the creation fails, memo it
    3. Try to delete a subvolume on the subvolume_group name
    4. If the deletion fails, memo it.
    5. If the creation and deletion are failed, return 0
    
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-Y1QYSK/
https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83573428

Signed-off-by: julpark-rh <yonhyun@gmail.com>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2022-05-15 18:33 UTC, AmarnatReddy commented on tests/cephfs/cephfs_vol_management/cephfs_vol_mgmt_volume_with_exist_names.py
> +        log.info(e)
can you change log.info --> log.error in exception block

2022-05-17 08:00 UTC, hkadam134 requested changes
Please change it to :
except Exception as e:
        log.error(e)
        log.error(traceback.format_exc())

2022-05-17 10:29 UTC, julpark-rh commented
> Please change it to : except Exception as e: log.error(e) log.error(traceback.format_exc())

I have changed those

2022-05-18 05:29 UTC, hkadam134 approved these changes
Looks good to me..

2022-05-18 18:58 UTC, AmarnatReddy approved these changes
LGTM

2022-05-18 18:58 UTC, merged