[Test] CEPH-83573775 - Added Test Case for disconnected Installation
red-hat-storage/cephci pull request #1628
Opened 2022-07-14 23:53 UTC by msainiRedhat

Signed-off-by: Manisha Saini <msaini@msaini.blr.csb>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2022-07-15 11:24 UTC, psathyan requested changes
Thanks for raising this PR.

Can we connect offline as I would like to review why the design and requirements?

2022-07-15 11:24 UTC, psathyan commented on ceph/ceph_admin/cephadm_ansible.py
> +        if "network-node" in roles:
The roles that are mentioned here have a one to one mapping with the daemon types listed in `ceph`. As `network-node` is not one of them, I would like us to not add this here. This breaks our design.

2022-07-15 11:24 UTC, psathyan commented on ceph/ceph_admin/cephadm_ansible.py
> +                cmd += f" -e 'custom_repo_url=http://{network_node_hostname}/repo/ceph-Tools'"
If I understand correctly, in the case of disconnected install the following is true
- ceph tools repo is internally hosted
- container image registry is internally hosted

If correct, then we don't need to add any code changes and the testing can be done via the CLI options

`--add-repo` can be used to the tools repo

In `.cephci.yaml`, you would need to modify the `registry_credentials` section to point to the right one.

2022-07-15 11:24 UTC, psathyan commented on conf/pacific/cephadm/disconnected_installation.yaml
> +---
Going down the path of not having `network-node`... I believe we can avoid this configuration and reuse the existing ones.

2022-07-26 05:39 UTC, psathyan commented
@msainiRedhat Would you like to continue using this PR or would it make sense to create another one for the required changes?

2022-07-28 18:59 UTC, msainiRedhat commented
@psathyan I will create another one for the required changes

2022-08-15 11:01 UTC, psathyan commented
> @psathyan I will create another one for the required changes

@msainiRedhat Please go ahead close this one.

2022-08-16 05:31 UTC, vdas-redhat commented
@msainiRedhat Can we close this PR ?

2022-08-17 13:24 UTC, closed without merging

2022-08-17 13:26 UTC, msainiRedhat commented
as per latest discussion, there are no changes required for disconnected installation. Closing this pull request as these changes are not needed