Updated metadata for suite executed only in PSI env
red-hat-storage/cephci pull request #1650
Opened 2022-07-21 06:25 UTC by sunilangadi2

Signed-off-by: Sunil Angadi <sangadi@redhat.com>

# Description
Fixes: RHCEPHQE-4473
To fix the issue https://github.com/red-hat-storage/cephci/issues/1592
In IBM environment, we don't have release.yaml file access hence this cron pipeline job suite is failing 
these suites can only be executed in psi-only environments
Hence updated metadata related to that suite.

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2022-07-25 07:34 UTC, manasagowri requested changes
Also please check in 5.1.yaml as well there is a test suite for multipath upgrade. Please make that also as openstack-only.

2022-07-25 07:34 UTC, manasagowri commented on pipeline/metadata/4.3.yaml
> -    - ibmc
Please add another tag - openstack-only

2022-07-25 09:41 UTC, sunilangadi2 commented on pipeline/metadata/4.3.yaml
> -    - ibmc
Done the changes.

2022-07-25 09:42 UTC, sunilangadi2 commented
Thanks @manasagowri for the review 
Addressed the comments please review it.

2022-07-25 12:34 UTC, manasagowri submitted a review, later dismissed
LGTM

2022-07-25 12:43 UTC, psathyan commented on pipeline/metadata/4.3.yaml
>      - openstack
should we also remove `openstack`?

2022-07-26 07:33 UTC, sunilangadi2 commented on pipeline/metadata/4.3.yaml
>      - openstack
Done.

2022-07-26 07:36 UTC, sunilangadi2 commented
Thanks @psathyan for the review, yes `openstack` becomes redundant when we have `openstack-only` value
Removed it, Please review it.

2022-07-26 07:39 UTC, psathyan approved these changes

2022-07-26 07:40 UTC, merged