Disable Trash feature and Verify
red-hat-storage/cephci pull request #1733
Opened 2022-08-17 11:58 UTC by preethisn

Description -Disable Trash feature, Update the config settings and  delete images and check if they are not moved to trash automatically

2022-08-17 11:59 UTC, preethisn commented
Logs are uploaded in -> http://magna002.ceph.redhat.com/ceph-qe-logs/Preethi/cephci-run-S0VCVQ/

2022-08-18 05:43 UTC, VasishtaShastry commented on tests/rbd/rbd_trash.py
> +    5. Disable "rbd_move_to_trash_on_remove" in client config and verify images are not moved to trash automatically
Can we please update module doc with 
1) NEw Testcae id and summary
2) clarify in flow that 4th and 5th step are for different TCs ?

2022-08-19 10:23 UTC, VasishtaShastry requested changes

2022-08-19 10:23 UTC, VasishtaShastry commented on tests/rbd/rbd_trash.py
> +                raise ImageFoundError(" Image is found in the Trash")
many lines here are replicated, can we try to optimise?

2022-08-20 06:07 UTC, preethisn commented
Addressed the review comments, latest logs are attached
http://magna002.ceph.redhat.com/ceph-qe-logs/Preethi/cephci-run-UQZNJ7/

2022-08-22 09:44 UTC, VasishtaShastry approved these changes

2022-08-22 09:45 UTC, Manohar-Murthy approved these changes
lgtm.

2022-08-22 09:46 UTC, merged