Adding rp link to results
red-hat-storage/cephci pull request #1988
Opened 2022-11-28 10:41 UTC by AmarnatReddy

Adding rp link to results 
As part of this PR, we are Collecting the Report Portal Url from the Upload results function and populating it as part of Test Artifacts in the Email Notification for IBM-C

For PSI,
We are going to populate the Report portal URL as a separate file in run_summary.json inside the logs_dir

Signed-off-by: Amarnath K <amk@amk.remote.csb>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2022-11-29 04:05 UTC, anrao19 approved these changes

2022-11-29 07:59 UTC, manasagowri requested changes
Just a minor change, rest looks good to me.

2022-11-29 10:10 UTC, tintumathew10 submitted a review, later dismissed
Looks good.

2022-12-06 12:26 UTC, ckulal reviewed
Looks good

2022-12-06 12:32 UTC, anrao19 approved these changes

2022-12-06 13:10 UTC, tintumathew10 reviewed
Changes are looking good.

2022-12-07 06:27 UTC, manasagowri approved these changes
LGTM

2022-12-07 06:28 UTC, merged