fixes shrink-mon script
red-hat-storage/cephci pull request #199
Opened 2020-08-25 15:21 UTC by Ameenasuhani

# Description
fixes issue https://github.com/red-hat-storage/cephci/issues/173

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs

# Checklist:

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test

2020-08-27 11:56 UTC, rakeshgm approved these changes

2020-08-27 12:11 UTC, rakeshgm commented
@XDsubhash or @sunilkumarn417 WDYT ?

2020-08-27 15:22 UTC, sunilkumarn417 requested changes
just a suggestion to take a look around the scenario, 

-  In one of the case, `ceph` wont respond until quorum is formed. whether do we need check flag to go forcefully shrink the MON, even though we know it may go out of quorum and ceph CLI won't respond. 

do we need to address these kind of scenarios and provide better task module with respect to shrink mon functionality.

2020-08-27 15:22 UTC, sunilkumarn417 commented on tests/ceph_ansible/shrink_mon.py
I would suggest print out inventory before and after update, so content of inventory will be good in case of issues/failures.

2020-08-27 15:22 UTC, sunilkumarn417 commented on tests/ceph_ansible/shrink_mon.py
> +    if build.startswith('4'):
please add comments at each important step, so that the module readability will be easier.

2020-08-27 15:22 UTC, sunilkumarn417 commented on tests/ceph_ansible/shrink_mon.py
> +        cmd = 'export ANSIBLE_DEPRECATION_WARNINGS=False ; cd {ansible_dir} ;ansible-playbook -vvvv -e \
Is this `export` not called in the ceph ansible task?

2020-08-27 15:22 UTC, sunilkumarn417 commented on tests/ceph_ansible/shrink_mon.py
>  import logging
please add module doc string

2020-08-27 15:22 UTC, sunilkumarn417 commented on tests/ceph_ansible/shrink_mon.py
> +        cmd = 'export ANSIBLE_DEPRECATION_WARNINGS=False ; cd {ansible_dir} ;ansible-playbook -vvvv -e \
since `export` is common between if and else block, can it framed earlier and add file path to command line as it relative `if-else` check.

2020-08-27 15:22 UTC, sunilkumarn417 commented on tests/ceph_ansible/shrink_mon.py
would suggest to create definition to display inventory info.

2020-08-28 06:38 UTC, Ameenasuhani commented
Logs:http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1598563329483/

2020-08-28 06:44 UTC, Ameenasuhani commented
The intermittent issue seen in logs where mon is out of quorum could be addressed as a different issue.    
I think mon out of quorum issue is seen because of split-brain( where we have even number of mons )

2020-08-28 11:49 UTC, Ameenasuhani commented
Passed logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1598610219031/

2020-09-04 06:33 UTC, rakeshgm approved these changes

2020-09-04 09:08 UTC, sunilkumarn417 requested changes

2020-09-04 09:08 UTC, sunilkumarn417 commented on tests/ceph_ansible/shrink_mon.py
> +        cmd = 'cd {ansible_dir} ;ansible-playbook -vvvv -e \
Would be good if we make common command string and update using if else block.

for example:
```
cmd = "ansible-playbook -i hosts {playbook}"

if condition1:
    playbook = "infra/site1.yml"
else:
    playbook = "site.yml"

client.exec_command(cmd=cmd.format(playbook=playbook))
```

2020-09-04 11:23 UTC, sunilkumarn417 requested changes

2020-09-04 11:23 UTC, sunilkumarn417 commented on tests/ceph_ansible/shrink_mon.py
> +        if re.match("%s" % matched_short_names[0], node):
do we need `re` here? can it be handled by `in` built-in function.

2020-09-13 15:28 UTC, Ameenasuhani commented
Logs:
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1600008489805/result.html
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1600004837999/result.html

2020-09-15 05:44 UTC, sunilkumarn417 approved these changes

2020-09-15 05:47 UTC, merged