Adding missing test suite for RHCS 6.0
red-hat-storage/cephci pull request #2048
Opened 2022-12-17 09:34 UTC by rkhambad

Signed-off-by: Rajendra Khambadkar <rkhambad@rkhambad.remote.csb>

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2022-12-20 11:22 UTC, VasishtaShastry approved these changes

2022-12-20 11:24 UTC, VasishtaShastry requested changes
Sorry, we need changes in utils to be in place before we merge this
Reverting my approval

2022-12-22 12:15 UTC, VasishtaShastry approved these changes

2022-12-22 16:30 UTC, Manohar-Murthy approved these changes

2022-12-22 16:31 UTC, merged