[quincy][pipeline][cephadm] metadata change
red-hat-storage/cephci pull request #2117
Opened 2023-01-24 06:35 UTC by MohitBis

[quincy][pipeline][cephadm] metadata change

Remove ibm cloud run for suite "tier-2_multiple_subnet_openstack_only.yaml"

2023-01-24 06:41 UTC, pranavprakash20 requested changes

2023-01-24 06:41 UTC, pranavprakash20 commented on pipeline/metadata/6.0.yaml
>        - openstack
Please change to `openstack-only`

2023-01-24 06:44 UTC, MohitBis commented on pipeline/metadata/6.0.yaml
>        - openstack
Updated

2023-01-24 06:48 UTC, vamahaja commented
Update commit message

2023-01-24 06:58 UTC, vamahaja approved these changes

2023-01-24 07:12 UTC, pranavprakash20 approved these changes
LGTM

2023-01-27 05:28 UTC, merged

2023-01-30 07:13 UTC, vdas-redhat commented
LGTM