Adapt test-image-delete-from-primary to test for both ecpools and replicated pools
red-hat-storage/cephci pull request #2175
Opened 2023-02-07 17:49 UTC by rkhambad

Signed-off-by: Rajendra Khambadkar <rkhambad@rkhambad.remote.csb>

Goal is to adapt test-image-delete-from-primary to test for both ecpools and replicated pools.
Modified module :

2023-02-09 10:39 UTC, sunilangadi2 requested changes

2023-02-09 10:39 UTC, sunilangadi2 commented on tests/rbd_mirror/test-image-delete-primary-site.py
> +    return 0
if `mirror_obj` empty still it's returing 0 so better add `return 0` inside if and `return 1` outside if

2023-02-09 10:58 UTC, sunilangadi2 commented on tests/rbd_mirror/test-image-delete-primary-site.py
> +    return 0
In team review we thought of taking that scenario as common for all methods hence resolving it now.

2023-02-09 10:58 UTC, sunilangadi2 approved these changes

2023-02-14 08:04 UTC, manasagowri approved these changes
group review done.

2023-02-14 08:05 UTC, merged