Add TC CEPH-83573802
red-hat-storage/cephci pull request #2529
Opened 2023-04-27 19:12 UTC by sayaleeraut

Adding test case for CEPH-83573802 - Verify the cluster status when ongoing operation are stopped ( abrupt/crash) - Tier4

# Description
1. Bootstrap cluster  using cephadm    
2. Copy SSH keys to nodes and Add them to cluster with address and role labels attached to them    
3. Deploy all daemon services using cephadm   
4. Perform the same steps serially for all daemons and check ceph status:syntax: systemctl stop <ceph-daemon.service>
    Eg: systemctl stop ceph-osd@6.service
5. Check if the service is stopped
    # sytemctl status ceph-osd@6.service    
    The service should be stopped successfully
6. Verify the ceph status
    #ceph -s

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-04-28 06:03 UTC, vamahaja requested changes

2023-04-28 06:03 UTC, vamahaja commented on tests/cephadm/test_systemctl_ops_on_osd_service.py
> +        if _status.split(' ', 1)[0] == status:
use `_status.contains(_status)`

2023-06-06 07:52 UTC, vamahaja requested changes

2023-06-06 07:52 UTC, vamahaja commented on tests/cephadm/test_osd_service_operations.py
> +class ClientIsMissingError(Exception):
Replace this with - https://github.com/red-hat-storage/cephci/blob/master/cli/exceptions.py#L20

2023-06-06 07:52 UTC, vamahaja commented on tests/cephadm/test_osd_service_operations.py
> +class CephClusterHealthError(Exception):
Replace this with - https://github.com/red-hat-storage/cephci/blob/master/cli/exceptions.py#L26

2023-06-06 07:52 UTC, vamahaja commented on tests/cephadm/test_osd_service_operations.py
> +class CephServiceStartError(Exception):
Replace this with - https://github.com/red-hat-storage/cephci/blob/master/cli/exceptions.py#L32

2023-06-06 07:52 UTC, vamahaja commented on tests/cephadm/test_osd_service_operations.py
> +class CephServiceFailError(Exception):
Replace this with - https://github.com/red-hat-storage/cephci/blob/master/cli/exceptions.py#L32

2023-06-06 07:52 UTC, vamahaja commented on cli/utilities/operations.py
> +            return True
Add extra line after for loop

2023-06-06 08:09 UTC, vamahaja requested changes

2023-06-06 08:09 UTC, vamahaja commented on tests/cephadm/test_osd_service_operations.py
> +LOG = Log(__name__)
Follow same pattern, change variable name to `log`

2023-06-06 08:09 UTC, vamahaja commented on tests/cephadm/test_osd_service_operations.py
> +    client = client[0]
More pythonic way -
```
client, osd_id = client[0], list()
```

2023-06-09 07:11 UTC, vamahaja requested changes

2023-06-09 07:11 UTC, vamahaja commented on suites/quincy/cephadm/tier-4-service-operations.yaml
>        module: test_cephadm.py
pacifci testsuite ?

2023-06-09 07:11 UTC, vamahaja commented
Code looks to me, @MohitBis please review.

2023-06-09 07:22 UTC, sayaleeraut commented on suites/quincy/cephadm/tier-4-service-operations.yaml
>        module: test_cephadm.py
Added for pacific as well

2023-06-14 15:52 UTC, merged

2023-06-14 15:52 UTC, vamahaja commented
Test results -

- 5.3 - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1npob/
- 6.1 - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-jm0tj