[Lib] Add support for fetching images from config
red-hat-storage/cephci pull request #2600
Opened 2023-05-29 10:18 UTC by pranavprakash20

Problem:
The disconnected installation requires the images to be added to the private registry created. Currently there is no way to accept these images.

Solution:
The solution proposed is to add the image details in the cephci.yaml file and add support to fetch these images for a given build_type (pacific/quincy etc.# )

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-05-30 07:01 UTC, vamahaja requested changes

2023-05-30 07:01 UTC, vamahaja commented on cephci/utils/configs.py
> +        raise ConfigError("Packages configurations are missing from config")
`Packages` ??

2023-05-30 07:01 UTC, vamahaja commented on cephci/utils/configs.py
> +        images = _images[build_type]
`return _get_images()[build_type]` would do same thing

2023-06-01 04:58 UTC, vamahaja requested changes
Add sample config here - https://github.com/red-hat-storage/cephci/blob/master/examples/cephci.yaml

2023-06-01 07:01 UTC, pranavprakash20 commented
> Add sample config here - https://github.com/red-hat-storage/cephci/blob/master/examples/cephci.yaml

Added sample config

2023-06-12 08:16 UTC, vamahaja requested changes

2023-06-12 08:16 UTC, vamahaja commented on examples/cephci.yaml
> +    - openshift4/ose-prometheus:v4.6 docker
`docker` ???

2023-06-13 03:06 UTC, pranavprakash20 commented on examples/cephci.yaml
> +    - openshift4/ose-prometheus:v4.6 docker
typo, removed.

2023-06-13 07:22 UTC, vamahaja approved these changes

2023-06-13 07:23 UTC, merged