Test to verify setting osd_memory_target on osd/host level
red-hat-storage/cephci pull request #2603
Opened 2023-05-30 17:26 UTC by msainiRedhat

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-05-31 06:21 UTC, vamahaja commented
Testruns -

    http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-yam5z
    http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-8v5vg

2023-05-31 14:38 UTC, vamahaja requested changes

2023-05-31 14:38 UTC, vamahaja commented on cli/ceph/ceph.py
> +        cmd += build_cmd_from_args(**kw)
Why separate statement ? Can't it be merged while declaring cmd ?

2023-05-31 14:38 UTC, vamahaja commented on cli/ceph/config.py
> +    def set_osd_memory_autotune(self, value):
`set_osd_memory_autotune` and `set_host_osd_memory_target` can be merged with `set` method

2023-05-31 14:38 UTC, vamahaja commented on cli/ceph/config.py
> +    def get_osd_memory_target(self, osd_id):
this should be converted to generic `get` method

2023-05-31 14:38 UTC, vamahaja commented on tests/cephadm/test_osd_memory_target.py
> +    if value_found:
More readable way -
```
    if not found:
        raise ConfigError(
            "osd_memory_target not found or has an incorrect value in ceph config"
        )
    log.info("osd memory target is validated in ceph config")

```

2023-05-31 14:38 UTC, vamahaja commented on tests/cephadm/test_osd_memory_target.py
> +            value_found = True
change this to `found`

2023-05-31 14:38 UTC, vamahaja commented on tests/cephadm/test_osd_memory_target.py
> +    out = cephadm.ceph.osd("tree", **kw)
instead add method `tree` here - https://github.com/red-hat-storage/cephci/blob/master/cli/ceph/osd/osd.py

2023-05-31 14:38 UTC, vamahaja commented on tests/cephadm/test_osd_memory_target.py
> +                osd_id = "osd." + str(osd_list[0])
Change this to `f"osd.{str(osd_list[0])}"`

2023-06-09 05:49 UTC, vamahaja requested changes

2023-06-09 05:54 UTC, vamahaja commented on cli/ceph/ceph.py
> +    def ceph_config(self, command, **kw):
Move this method to [1] accordingly
https://github.com/red-hat-storage/cephci/blob/master/cli/ceph/config.py

2023-06-09 06:00 UTC, vamahaja commented on cli/ceph/config.py
> +    def get(self, key, value):
`def get(self, who, key=None):`

2023-06-09 06:02 UTC, vamahaja commented on cli/ceph/config.py
> +        cmd = f"{self.base_cmd} get {key} {value}"
```
cmd = f"{self.base_cmd} get {who}"

if key:
     cmd += "{key}"
```

2023-06-09 11:58 UTC, msainiRedhat commented
Logs - http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-98yiv/

2023-06-09 15:02 UTC, vamahaja approved these changes

2023-06-09 15:02 UTC, merged