[CephMgr][Tier2] Verify enabling and disabling ceph-mgr plugins
red-hat-storage/cephci pull request #2639
Opened 2023-06-14 16:31 UTC by vinpapnoi

CEPH-11389
Verify enabling and disabling ceph-mgr plugins

- Deploy cluster
- Enable and disable the ceph-mgr plugins such as zabbix, prometheus, restful, influx, etc.

2023-06-14 16:48 UTC, vamahaja requested changes

2023-06-14 16:48 UTC, vamahaja commented on tests/mgr/test_cephmgr_plugins.py
> +                CephMgrPluginFailure(f"Failed to {step_to_validate} {plugin} plugin")
Add validation steps for plugins

2023-06-14 16:48 UTC, vamahaja commented on tests/mgr/test_cephmgr_plugins.py
> +                CephMgrPluginFailure(f"Failed to {step_to_validate} {plugin} plugin")
use exception - https://github.com/red-hat-storage/cephci/blob/master/cli/exceptions.py#L26

2023-06-15 05:41 UTC, vinpapnoi commented on tests/mgr/test_cephmgr_plugins.py
> +                CephMgrPluginFailure(f"Failed to {step_to_validate} {plugin} plugin")
Done

2023-06-15 05:41 UTC, vinpapnoi commented on tests/mgr/test_cephmgr_plugins.py
> +                CephMgrPluginFailure(f"Failed to {step_to_validate} {plugin} plugin")
Done

2023-06-23 06:22 UTC, vamahaja reviewed
@tintumathew10 @pranavprakash20 @MohitBis please review

2023-06-23 06:47 UTC, vinpapnoi commented
Test run logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-U47TKN

2023-06-23 06:48 UTC, pranavprakash20 approved these changes
LGTM

2023-06-23 11:20 UTC, vamahaja approved these changes

2023-06-23 11:21 UTC, merged