[Conf] Add Suite for NFS-Ganesha
red-hat-storage/cephci pull request #2648
Opened 2023-06-16 08:04 UTC by pranavprakash20

Problem: The aim is to define a new CI job specific for NFS Ganesha, which picks up nfs specific tests and can be extended with future tests adding into nfs component

Solution: Create a new suite specific to nfs, use the CI job to pick this suite and perform the valdiations.

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-06-16 09:11 UTC, vamahaja requested changes
LGTM

@tintumathew10 @MohitBis please review

2023-06-16 09:13 UTC, tintumathew10 approved these changes
LGTM

2023-06-16 09:19 UTC, MohitBis approved these changes

2023-06-19 04:53 UTC, msainiRedhat commented
LGTM

2023-06-19 04:55 UTC, msainiRedhat approved these changes

2023-06-26 05:03 UTC, vamahaja approved these changes

2023-06-26 05:04 UTC, merged