Test File ops renames and lookups on NFS mount
red-hat-storage/cephci pull request #2725
Opened 2023-07-13 00:03 UTC by msainiRedhat

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-07-13 02:34 UTC, pranavprakash20 approved these changes
LGTM

2023-07-14 00:15 UTC, msainiRedhat commented
Logs - http://magna002.ceph.redhat.com/ceph-qe-logs/msaini/Jenkins/rename_nfs/cepci-log/

2023-07-14 05:43 UTC, pranavprakash20 submitted a review, later dismissed
LGTM

2023-07-14 07:29 UTC, vamahaja requested changes

2023-07-14 07:29 UTC, vamahaja commented on cli/ceph/nfs/cluster/cluster.py
>          """
Use list
```
nfs_server = nfs_server if type(nfs_server) in (list, tuple) else [nfs_server]
nfs_server = " ".join(nfs_server)
```

2023-07-14 07:29 UTC, vamahaja commented on tests/nfs/test_file_ops_renames.py
> +    for i in range(1, num_files + 1):
It will take num_files * timeout secs in case of failed operation. To avoid this move this for loop within waiter loop

2023-07-14 07:29 UTC, vamahaja commented on tests/nfs/test_file_ops_renames.py
> +    for i in range(1, num_dirs + 1):
same as above

2023-07-14 07:29 UTC, vamahaja commented on tests/nfs/test_file_ops_renames.py
> +    for i in range(1, num_files + num_dirs):
Use `_` instead of `i`

2023-07-14 07:29 UTC, vamahaja commented on tests/nfs/test_file_ops_renames.py
> +            if "No such file or directory" in error_message:
Change this to -
```
            if not "No such file or directory" in error_message:
                raise OperationFailedError("failed to perform lookups")
            log.warning(f"Ignoring error: {error_message}")
```

2023-07-14 07:29 UTC, vamahaja commented on tests/nfs/test_file_ops_renames.py
> +    for client in [clients[0], clients[1], clients[2]]:
client[:2]

2023-07-19 09:52 UTC, pranavprakash20 commented
LGTM

2023-07-19 20:52 UTC, msainiRedhat commented
Logs - http://magna002.ceph.redhat.com/cephci-jenkins/msaini/nfs/cepci-log/

2023-07-20 03:11 UTC, MohitBis approved these changes
LGTM

2023-07-20 05:27 UTC, pranavprakash20 approved these changes
LGTM

2023-07-21 04:56 UTC, closed without merging