[Lib + Test Fix] Fix nfs tests and add nfs utils
red-hat-storage/cephci pull request #2743
Opened 2023-07-19 04:58 UTC by pranavprakash20

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-07-19 05:02 UTC, pranavprakash20 commented
run results will be attached once the rhos-d issue is resolved.

2023-07-19 09:59 UTC, MohitBis submitted a review, later dismissed
LGTM

Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-RG5WQT/

2023-07-19 19:43 UTC, msainiRedhat submitted a review, later dismissed
LGTM

2023-07-20 04:30 UTC, pranavprakash20 commented on cli/utilities/nfs_utils.py
> +        if out:
yes, so if the mount fails, we need to exit right? out will be 1, is the mount comd fails, so if out: then return false and exit the process.
Am I missing something?

2023-07-20 04:34 UTC, pranavprakash20 commented on cli/utilities/nfs_utils.py
> +        if out:
My mistake, got it. Will move return True outside loop

2023-07-20 04:36 UTC, MohitBis approved these changes
LGTM

2023-07-20 05:25 UTC, msainiRedhat approved these changes
LGTM

2023-07-20 07:01 UTC, vamahaja requested changes

2023-07-20 15:01 UTC, MohitBis approved these changes
LGTM

Working as expected with below as well
https://github.com/red-hat-storage/cephci/pull/2745
log : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-CQMR3C/

2023-07-20 15:11 UTC, msainiRedhat approved these changes
LGTM

2023-07-21 04:42 UTC, vamahaja approved these changes

2023-07-21 04:43 UTC, merged