[Test] Add test to validate rootsquash scenario
red-hat-storage/cephci pull request #2801
Opened 2023-08-03 06:14 UTC by pranavprakash20

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-08-03 06:17 UTC, pranavprakash20 commented
run log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-URZE3O/

2023-08-03 10:38 UTC, MohitBis approved these changes
LGTM

2023-08-03 10:42 UTC, msainiRedhat requested changes

2023-08-03 10:42 UTC, msainiRedhat commented on suites/quincy/nfs/tier-0_nfs_ganesha.yaml
> +        nfs_version: 4.2
Default should be 4.1 protocol

2023-08-03 10:59 UTC, MohitBis approved these changes
LGTM

2023-08-03 11:01 UTC, msainiRedhat approved these changes
LGTM

2023-08-10 07:30 UTC, vamahaja approved these changes

2023-08-10 07:31 UTC, merged