[Conf] Add nfs suites for Reef
red-hat-storage/cephci pull request #2820
Opened 2023-08-09 09:12 UTC by pranavprakash20

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-08-09 09:13 UTC, MohitBis submitted a review, later dismissed
LGTM

2023-08-10 07:47 UTC, vamahaja requested changes

2023-08-10 07:47 UTC, vamahaja commented on conf/reef/nfs/tier-0.yaml
> +globals:
Change suite name to `tier0`

2023-08-10 07:47 UTC, vamahaja commented on conf/reef/nfs/tier-1-8node.yaml
> +globals:
Change name to `12node-1admin-4client`

2023-08-10 07:47 UTC, vamahaja commented on suites/reef/nfs/tier-0_nfs_ganesha.yaml
> +#===============================================================================================
Change `tier-0` to `tier0` and replace `_` with `-`

2023-08-10 07:47 UTC, vamahaja commented on suites/reef/nfs/tier-1_nfs_ganesha.yaml
> +#===============================================================================================
Same as above

2023-08-11 04:51 UTC, pranavprakash20 commented
changes made

2023-08-17 13:05 UTC, vamahaja approved these changes

2023-08-17 13:05 UTC, merged