[NFS-Ganesha][Phase2]Add testcase automation
red-hat-storage/cephci pull request #2856
Opened 2023-08-24 07:08 UTC by MohitBis

[NFS-Ganesha][Phase2]Add testcase automation
Scenario: Hard links : Create files from C1 and create synlinks from C2 and perform lookups from C3

2023-08-24 08:52 UTC, MohitBis commented
Log : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-CCACYI/

2023-08-24 08:54 UTC, msainiRedhat approved these changes
LGTM

2023-08-25 05:47 UTC, pranavprakash20 submitted a review, later dismissed
LGTM

2023-08-25 05:49 UTC, vamahaja requested changes

2023-08-25 05:49 UTC, vamahaja commented on tests/nfs/nfs_verify_file_ops_hard_links.py
> +            sleep(0.5)
Add comment for explicit sleep

2023-08-25 05:49 UTC, vamahaja commented on tests/nfs/nfs_verify_file_ops_hard_links.py
> +        log.error(f"Error : {e}")
Add meaningful error message

2023-08-25 05:49 UTC, vamahaja commented on tests/nfs/nfs_verify_file_ops_hard_links.py
> +    finally:
return ???

2023-08-25 05:56 UTC, MohitBis commented on tests/nfs/nfs_verify_file_ops_hard_links.py
> +            sleep(0.5)
Updated

2023-08-25 05:56 UTC, MohitBis commented on tests/nfs/nfs_verify_file_ops_hard_links.py
> +        log.error(f"Error : {e}")
Updated

2023-08-25 05:56 UTC, MohitBis commented on tests/nfs/nfs_verify_file_ops_hard_links.py
> +    finally:
Updated

2023-08-25 07:02 UTC, vamahaja approved these changes

2023-08-25 07:02 UTC, merged