Multi io support
red-hat-storage/cephci pull request #2860
Opened 2023-08-25 06:21 UTC by pranavprakash20

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-08-30 04:03 UTC, vamahaja requested changes

2023-08-30 04:03 UTC, vamahaja commented on cli/io/linux_untar.py
> +                        clients (list):     Client (s)
Fix indentation

2023-08-30 04:03 UTC, vamahaja commented on cli/io/linux_untar.py
> +            cmd = (
Make it parameterize

2023-08-30 04:03 UTC, vamahaja commented on cli/io/linux_untar.py
> +                cmd = "cp /root/linux-5.4.54.tar.xz {}/{}".format(
same as above

2023-08-30 04:03 UTC, vamahaja commented on cli/io/linux_untar.py
> +                cmd = "cd {}/{};tar -xvf linux-5.4.54.tar.xz".format(
same as above

2023-08-30 04:03 UTC, vamahaja commented on cli/io/linux_untar.py
> +    def linux_untar(self):
change this to some common name like `start`

2023-08-30 04:03 UTC, vamahaja commented on cli/io/linux_untar.py
> +        self.mountpoint = config["clients"]
`config["clients"]` ???

2023-08-30 04:03 UTC, vamahaja commented on cli/io/__init__.py
> +        available_ios = ["specstorage", "linux_untar", "fio"]
supported platforms

2023-08-31 09:34 UTC, pranavprakash20 commented
Added support for smallfile and FIO

2023-08-31 09:34 UTC, pranavprakash20 commented
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-QNE0J1/

2023-09-04 05:20 UTC, MohitBis submitted a review, later dismissed
LGTM

2023-09-06 05:08 UTC, vamahaja requested changes

2023-09-06 05:08 UTC, vamahaja commented on cli/io/fio.py
> +class FioError(Exception):
Change this exception to `IOEroro` and move to - https://github.com/red-hat-storage/cephci/blob/master/cli/exceptions.py

2023-09-06 05:08 UTC, vamahaja commented on cli/io/fio.py
> +    def install_fio(self):
This should be part of installation step. Here in library assume that this package is present.

2023-09-06 05:08 UTC, vamahaja commented on cli/io/fio.py
> +        fio_config:
I assume these are test suite configs. Remove this and add description for parameters passed to this method

2023-09-06 05:08 UTC, vamahaja commented on cli/io/fio.py
> +        fio_configs = []
no need to use fio as prefix or postfix in this libarary. Change this in all places.

2023-09-06 05:08 UTC, vamahaja commented on cli/io/fio.py
> +        fio_config = f"""
Is this correct indentation? no pep8 error ?

2023-09-06 05:08 UTC, vamahaja commented on cli/io/fio.py
> +    ):
Add description to method

2023-09-06 05:08 UTC, vamahaja commented on cli/io/fio.py
> +            mount_dir (str): Mounting directory
missing description for some parameters

2023-09-06 05:08 UTC, vamahaja commented on cli/io/small_file.py
> +class SmallfileError(Exception):
Same as above

2023-09-06 05:08 UTC, vamahaja commented on cli/io/small_file.py
> +    def pull_smallfile_repo(self):
Same as above

2023-09-06 05:08 UTC, vamahaja commented on cli/io/small_file.py
> +        Runs small file IO
This is correct, follow same format for Fio lib

2023-09-06 05:08 UTC, vamahaja commented on cli/io/small_file.py
> +        cmd = "mkdir -p /var/tmp/smf"
don't we have method for this one in `CephNode` object ?

2023-09-06 05:08 UTC, vamahaja commented on cli/io/small_file.py
> +                f"python3 smallfile/smallfile_cli.py --operation {operation} --threads {threads} "
`python3 smallfile/smallfile_cli.py` create global variable for this script path and make it configuarable

2023-09-06 05:25 UTC, vamahaja commented on cli/io/small_file.py
> +        self.pull_smallfile_repo()
Move these setup part in cli/utilities/utils.py and use names like -

- setup_smallfile_io
- setup_fio

2023-09-07 11:24 UTC, pranavprakash20 commented
@vamahaja All review comments addressed, please re-review

2023-09-07 12:04 UTC, pranavprakash20 commented on cli/utilities/utils.py
> +def install_fio(client):
<comment> chage to setup_fio

2023-09-07 16:25 UTC, vamahaja approved these changes

2023-09-07 16:25 UTC, merged