[Nfs]Add test to validate lookups while mutliple IO in progress
red-hat-storage/cephci pull request #2865
Opened 2023-08-28 04:41 UTC by pranavprakash20

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-08-28 04:53 UTC, MohitBis submitted a review, later dismissed
LGTM

2023-08-28 05:29 UTC, msainiRedhat requested changes

2023-08-28 05:29 UTC, msainiRedhat commented on suites/reef/nfs/tier1-nfs-ganesha-phase2.yaml
> +        nfs_version: 4.2
Use mount version as v4.1

2023-08-30 04:49 UTC, vamahaja requested changes

2023-08-30 04:49 UTC, vamahaja commented on tests/nfs/nfs_verify_multiple_parallel_io_and_lookups.py
> +from cli.io.io import linux_untar
Update this based on new changes

2023-08-31 09:57 UTC, msainiRedhat approved these changes
LGTM

2023-09-04 05:22 UTC, MohitBis approved these changes
LGTM

2023-09-06 05:13 UTC, vamahaja commented on tests/nfs/nfs_verify_multiple_parallel_io_and_lookups.py
> +from cli.io.io import linux_untar
My bad, this is correct import.

2023-09-06 05:29 UTC, vamahaja approved these changes

2023-09-06 05:29 UTC, merged