Adding FS TC 83575196 NFS HA Failover
red-hat-storage/cephci pull request #2899
Opened 2023-09-06 08:18 UTC by AmarnatReddy

# Description
Adding FS TC 83575196 NFS HA Failover
Polarion : https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83575196 
Procedure
    Create default NFS HA Deployment and Reboot the node while IOs are going
    1. Log into the Cephadm shell:
        Example
        [root@host01 ~]# cephadm shell
    2. Create the NFS cluster with the --ingress flag:
        Syntax
        ceph nfs cluster create CLUSTER-ID [PLACEMENT] [--port PORT_NUMBER] [--ingress --virtual-ip IP_ADDRESS]
    3. Validate the Service is UP
    4. Mount using the Virtual IP.
    5. Get active Nfs node
    5. Create Export and write IO and reboot nfs node in parallel
    6. Cleanup
    
Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-IRGRHV/   

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-09-06 15:15 UTC, hkadam134 commented on suites/pacific/cephfs/tier-2_cephfs_test-nfs_ha.yaml
> +  - test:
Even the Polarion ID needs to be updated.

2023-09-06 15:15 UTC, hkadam134 commented on tests/cephfs/cephfs_nfs/test_cephfs_nfs_ha_failover.py
> +        tc = "CEPH-83575000"
Update the Polarion TC ID.

2023-09-13 08:45 UTC, sumabai requested changes

2023-09-13 08:45 UTC, sumabai commented on tests/cephfs/cephfs_nfs/test_cephfs_nfs_ha_failover.py
> +        log.info("validate the services hace started on nfs")
spell error : hace -> have

2023-09-14 17:15 UTC, hkadam134 commented on suites/pacific/cephfs/tier-2_cephfs_test-nfs_ha.yaml
> +      name: nfs-ha-create-using-spec-ingress
name needs to be changed.

2023-09-14 18:38 UTC, hkadam134 approved these changes
Looks Good

2023-09-15 06:28 UTC, neha-gangadhar approved these changes

2023-09-15 06:29 UTC, merged