[Reef][UPI]Add upi suite
red-hat-storage/cephci pull request #2904
Opened 2023-09-07 07:41 UTC by MohitBis

[Reef][UPI]Add upi suite

2023-09-07 07:51 UTC, MohitBis commented
Logs:
Deployment: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-IOLOR7/
Upgrade 6x to 7x: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-W7MAKJ/
Upgrade 5x to 7x: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-EXDDGE/

2023-09-14 04:30 UTC, pranavprakash20 submitted a review, later dismissed
LGTM

2023-09-14 05:11 UTC, vamahaja requested changes
Add step to validate cluster status after performing IOs

2023-09-14 06:04 UTC, vamahaja approved these changes

2023-09-14 06:05 UTC, merged