Adding FS TC 83575781
red-hat-storage/cephci pull request #3007
Opened 2023-10-10 19:44 UTC by AmarnatReddy

# Description
Adding FS TC 83575781
CEPH-83575781 - Allow entries to be removed from lost+found directory in File System

        Steps to create lost+found directory in FS
        1. Create filesystem
        2. mount the Fs
        3. write data
        4. purge the metadata pool
        5. get rados objects from the data written and deleta object
        6. Reset the sessions,snaps,inodes and file system
        7. Fail the Fs
        8. Reset the FS
        9. Initate recovery tools on FS
        10. This will create lost+found dir

        As part of TC delete the contents on lost+found  directory

Logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-OAHVRP
Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-10-13 04:31 UTC, hkadam134 requested changes

2023-10-13 04:31 UTC, hkadam134 commented on tests/cephfs/cephfs_bugs/test_rm_on_lost_found_dir.py
> +        client1.exec_command(sudo=True, cmd=f"umount {fuse_mount_dir}", check_ec=False)
@AmarnatReddy - Can you also include the deletion of the mounting directory on client?

2023-10-13 04:31 UTC, hkadam134 commented on tests/cephfs/cephfs_bugs/test_rm_on_lost_found_dir.py
> +        out, rc = client1.exec_command(sudo=True, cmd=f"ls -lrt {fuse_mount_dir}")
Can we have the output of this list captured in the logs?

2023-10-16 04:45 UTC, sumabai commented on tests/cephfs/cephfs_bugs/test_rm_on_lost_found_dir.py
> +        client1.exec_command(sudo=True, cmd=f"rm -rf {fuse_mount_dir}/lost+found/*")
As above, capturing contents of lost_found dir and displaying in logs before deleting would be desired.

2023-10-16 04:45 UTC, sumabai commented on tests/cephfs/cephfs_bugs/test_rm_on_lost_found_dir.py
> +        log.info("We are able to delete contents of lost+found dir")
performing ls on lost+found and verifying that no more contents left in lost+found may be good

2023-10-16 05:11 UTC, sumabai approved these changes

2023-10-16 18:02 UTC, hkadam134 approved these changes
LGTM

2023-10-17 05:56 UTC, neha-gangadhar commented
@AmarnatReddy please add the test to reef folder suite as well.

2023-10-17 07:20 UTC, neha-gangadhar approved these changes
lgtm

2023-10-17 07:22 UTC, merged