[Test] Add test to validate crash log creation
red-hat-storage/cephci pull request #3131
Opened 2023-11-15 04:52 UTC by pranavprakash20

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-11-15 10:35 UTC, pranavprakash20 commented
run log : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-C5Y358/

2023-11-20 06:36 UTC, vamahaja requested changes

2023-11-20 06:36 UTC, vamahaja commented on tests/cephadm/test_verify_crash_reports.py
> +    cmd = "pgrep osd"
can't we use - https://github.com/red-hat-storage/cephci/blob/master/cli/utilities/utils.py#L599 ? If no then create generic method and add ^^^

2023-11-20 06:36 UTC, vamahaja commented on tests/cephadm/test_verify_crash_reports.py
> +    cmd = f"kill -s SIGSEGV {pid_to_kill}"
Same as above

2023-11-20 06:36 UTC, vamahaja commented on tests/cephadm/test_verify_crash_reports.py
> +        cmd = f"ls {folder}"
Use - https://github.com/red-hat-storage/cephci/blob/master/ceph/ceph.py#L2074

2023-11-22 05:49 UTC, pranavprakash20 commented
@vamahaja all review comments addressed

updated run log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-Q7VECJ/

2023-11-22 12:21 UTC, vamahaja requested changes

2023-11-22 12:21 UTC, vamahaja commented on cli/utilities/utils.py
> +        cmd = f"kill -s SIGSEGV {pid}"
Why separate command for each pid ? Can't we pass list of pids ?

2023-11-22 12:21 UTC, vamahaja commented on tests/cephadm/test_verify_crash_reports.py
> +    if not log_found:
no need to have this logic, test case should fail even one directory fails to generate crash logs.

2023-11-28 04:18 UTC, vamahaja approved these changes

2023-11-28 04:19 UTC, merged