[Test][Cephadm] Add test to validate pid limit of services
red-hat-storage/cephci pull request #3153
Opened 2023-11-20 11:46 UTC by pranavprakash20

# Description

CEPH-83575590 - RHEL 9 (cgroups v2) - the pid limits ARE enforced as compared to RHEL8 (cgroup v1)

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-11-20 11:47 UTC, pranavprakash20 commented
run log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1ZJM0U/

2023-11-21 04:03 UTC, vamahaja requested changes

2023-11-21 04:03 UTC, vamahaja commented on cli/utilities/utils.py
> +    cmd = f"podman ps | grep {service}"
Add method for this step here - https://github.com/red-hat-storage/cephci/blob/master/cli/utilities/containers.py#L47

2023-11-21 04:03 UTC, vamahaja commented on cli/utilities/utils.py
> +    cmd = f"podman inspect {process_name}  | grep -i pids-limit"
instead use - https://github.com/red-hat-storage/cephci/blob/master/cli/utilities/containers.py#L151

2023-11-21 04:03 UTC, vamahaja commented on tests/cephadm/test_validate_pid_limit.py
> +log = Log(__name__)
Unused variable

2023-11-22 09:56 UTC, pranavprakash20 commented
All review comments addressed
New run log: 

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-64XLB6/

2023-11-22 12:24 UTC, vamahaja requested changes

2023-11-22 12:24 UTC, vamahaja commented on cli/utilities/containers.py
> +            cmd += f" | grep -i {grep}"
instead use `--filter` parameter. Refer - https://docs.podman.io/en/stable/markdown/podman-images.1.html

2023-11-22 12:24 UTC, vamahaja commented on cli/utilities/containers.py
> +            cmd += f" | grep -i {grep}"
same as above, refer - https://docs.podman.io/en/stable/markdown/podman-ps.1.html

2023-11-27 06:56 UTC, pranavprakash20 commented
new run log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-9R39ER/

2023-11-28 03:44 UTC, vamahaja requested changes

2023-11-28 03:44 UTC, vamahaja commented on cli/utilities/containers.py
> +            cmd += f" | grep -i {grep}"
My bad. 

Don't add grep here. Get the data through this lib and then parse it accordingly in the test.

2023-11-28 03:44 UTC, vamahaja commented on cli/utilities/utils.py
> +    log.info(process_name)
not much data, please remove

2023-11-28 03:44 UTC, vamahaja commented on cli/utilities/utils.py
> +    log.info(process_name)
not much data, please remove

2023-11-28 13:31 UTC, vamahaja reviewed
LGTM

2023-11-29 04:27 UTC, tintumathew10 approved these changes
LGTM

2023-11-29 04:35 UTC, merged