Automation of the CEPH-9369 - RADOS: Time scheduled scrubbing: Observe cpu and memory usage during scrubbing
red-hat-storage/cephci pull request #3159
Opened 2023-11-21 06:59 UTC by SrinivasaBharath

# Description

Test Case: CEPH-9369 - RADOS: Time scheduled scrubbing: Observe cpu and memory usage during scrubbing

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [x] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2023-11-21 08:00 UTC, SrinivasaBharath commented
The code is not tested. Please review the logic of the code.

2023-11-21 09:18 UTC, pdhiran commented on tests/rados/test_scrub_cpu_memory_usage.py
> +import datetime
please add docstrings for the module

2023-11-24 04:19 UTC, SrinivasaBharath commented on tests/rados/test_scrub_cpu_memory_usage.py
> +import datetime
Added the doc string.

2023-11-24 05:01 UTC, SrinivasaBharath commented
Test execution is in progress.

2023-11-27 22:37 UTC, harshkumarRH requested changes
@SrinivasaBharath please make the small changes so we can merge this

2023-11-29 07:53 UTC, SrinivasaBharath commented on tests/rados/test_scrub_cpu_memory_usage.py
> +    scrub_object.set_osd_configuration("osd_scrub_end_hour", 0)
Configuration are setting default by using the ceph osd rm config

2023-11-29 07:54 UTC, SrinivasaBharath commented on tests/rados/test_scrub_cpu_memory_usage.py
> +        log.error(f"Exception hit while command execution. {er}")
Added the return statement.

2023-11-29 08:31 UTC, SrinivasaBharath commented
Reef Pass Log- http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-FRX86B

2023-11-29 09:51 UTC, pdhiran reviewed
looks good

2023-11-30 00:36 UTC, harshkumarRH approved these changes
LGTM

2023-11-30 03:47 UTC, pdhiran approved these changes

2023-11-30 03:48 UTC, merged