Object lock with no overwrite , tracks BZ BZ 1890843
red-hat-storage/cephci pull request #3226
Opened 2023-12-13 06:58 UTC by TejasC88

Description:
- Create bucket with bucket lock enabled
- Upload key1 with 2 minutes of retention time , and try deletion before retention time passes
- Delete key1 post retention time expiry
- Upload key with 2 minutes retention in GOVERNANCE mode
- Extend retention time to 3 minutes, and try deletion before retnetion period 
- Delete key2 with bypass-governance-retention option

Pass log : http://magna002.ceph.redhat.com/ceph-qe-logs/tejas/cephci-run-5IFHXH/

2023-12-13 07:21 UTC, ckulal requested changes
Please include testcase in reef suite aswell

2023-12-13 11:26 UTC, TejasC88 commented
> Please include testcase in reef suite aswell

Reef has failure since bz is not yet fixed in 7.0 . I have added known issue. Request you to review .
Fail log : http://magna002.ceph.redhat.com/ceph-qe-logs/tejas/cephci-run-012K2J/

2023-12-13 12:52 UTC, TejasC88 commented
> Hi @TejasC88 , In reef suite, https://github.com/red-hat-storage/cephci/blob/master/suites/reef/rgw/tier-2_rgw_regression_test.yaml
> 
> Since we already have large number of test cases, which increases cephci execution time. Hence we have created one more extended suite, request to add new test case into this suite: https://github.com/red-hat-storage/cephci/blob/master/suites/reef/rgw/tier-2_rgw_regression_extended.yaml

Thanks @ckulal , added to the extended regression suite.

2023-12-14 04:03 UTC, ckulal commented on suites/reef/rgw/tier-2_rgw_regression_test.yaml
> +  # Object lock no overwrite
Please remove this testcase from this suite.

2023-12-14 08:06 UTC, ckulal reviewed
LGTM

2023-12-14 09:31 UTC, anrao19 approved these changes

2023-12-14 10:24 UTC, ckulal approved these changes

2023-12-14 10:25 UTC, merged