Adding new folio config files
red-hat-storage/cephci pull request #3426
Opened 2024-02-22 06:58 UTC by tintumathew10

# Description

Adding new folio config files.

2024-02-27 07:55 UTC, vamahaja requested changes

2024-02-27 07:55 UTC, vamahaja commented on conf/baremetal/folio1_1admin_4node_4client.yaml
> +        -
Correct indentation

2024-02-27 09:48 UTC, vamahaja requested changes

2024-02-27 09:48 UTC, vamahaja commented on suites/reef/baremetal/nfs_folio3_3node_4client.yaml
> +  # -
Remove commented tests

2024-02-27 09:48 UTC, vamahaja commented on conf/baremetal/nfs_folio3_1admin_3node_4client.yaml
> +  -
Fix indentation

2024-02-27 09:48 UTC, vamahaja commented on conf/baremetal/folio2_1admin_4node_4client.yaml
> +  -
Fix indentation

2024-02-27 09:48 UTC, vamahaja commented on conf/baremetal/folio1_1admin_4node_4client.yaml
> +  -
Fix indentation

2024-02-29 05:52 UTC, tintumathew10 commented on conf/baremetal/folio1_1admin_4node_4client.yaml
> +  -
done

2024-02-29 05:59 UTC, vamahaja approved these changes

2024-02-29 05:59 UTC, merged