Adding small file writes to scale tests
red-hat-storage/cephci pull request #3834
Opened 2024-06-27 11:16 UTC by hkadam134

# Description

Summary: 
* The script manages CephFS operations on a Ceph cluster. It initializes clients and subvolumes, mounts them using FUSE or kernel, and runs smallfile IO operations in parallel. 
* It periodically logs Ceph cluster details and collects MDS logs, which are compressed after testing. 
* The script uses threading to handle concurrent logging and IO operations efficiently.

Logs : 
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-X17M8C/
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-J6T4YU/

Ex : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-J6T4YU/sf_w_kernel_10_cl_10_subv_create_ops_1_th_100000_files_1024_size/

This folder has all ceph cluster details like, logs, health status, top etc.

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2024-06-27 15:01 UTC, sumabai approved these changes
lgtm

2024-06-27 15:02 UTC, sumabai requested changes
Please resolve tox issues

2024-07-02 06:54 UTC, neha-gangadhar reviewed
lgtm

2024-07-03 13:46 UTC, AmarnatReddy commented on tests/cephfs/cephfs_scale/small_file_writes.py
> +def get_daemon_names(client, deamon_type):
Do you want to move this to fs utils file. as this can be reused

2024-07-12 04:10 UTC, closed without merging