[Test] Validate the /config endpoint of RESTful module
red-hat-storage/cephci pull request #4059
Opened 2024-09-04 11:31 UTC by sayaleeraut

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2024-09-04 11:43 UTC, pranavprakash20 approved these changes
LGTM

2024-09-04 11:45 UTC, MohitBis approved these changes
LGTM

2024-09-05 06:12 UTC, sayaleeraut commented
Execution logs - https://ocs3xstage-jenkins-csb-rhgsocs3x.apps.ocp-c1.prod.psi.redhat.com/view/Executor/job/qe-squid-test-executor-openstack/26/console

2024-09-06 06:05 UTC, vamahaja requested changes

2024-09-06 06:05 UTC, vamahaja commented on tests/mgr/test_restful_operations_config_endpoint.py
> +    return 0
this code is not reachable

2024-09-06 06:05 UTC, vamahaja commented on tests/mgr/test_restful_operations_config_endpoint.py
> +    username = config.get("username")
better to have single check -
```
if not (username and endpoint and method and status_code):
    raise ....
```

2024-09-06 06:05 UTC, vamahaja commented on tests/mgr/test_restful_operations_config_endpoint.py
> +    raise OperationFailedError(
Move this exception to `run` method

2024-09-09 06:57 UTC, sayaleeraut commented on tests/mgr/test_restful_operations_config_endpoint.py
> +    username = config.get("username")
Done, please check L50

2024-09-09 06:57 UTC, sayaleeraut commented on tests/mgr/test_restful_operations_config_endpoint.py
> +    return 0
Done, made correction

2024-09-09 06:57 UTC, sayaleeraut commented on tests/mgr/test_restful_operations_config_endpoint.py
> +    raise OperationFailedError(
Done

2024-09-09 07:08 UTC, pranavprakash20 approved these changes
LGTM

2024-09-10 07:38 UTC, vamahaja commented on tests/mgr/test_restful_operations_config_endpoint.py
> +            )
Add extra line

2024-09-10 07:38 UTC, vamahaja commented on tests/mgr/test_restful_operations_config_endpoint.py
> +
Add comment

2024-09-10 09:08 UTC, sayaleeraut commented on tests/mgr/test_restful_operations_config_endpoint.py
> +    for _config in [username, endpoint, method, status_code]:
I added it to get the exact missing config information through error msg in L52

2024-09-12 07:26 UTC, sayaleeraut commented
Execution logs -
https://ocs3xstage-jenkins-csb-rhgsocs3x.apps.ocp-c1.prod.psi.redhat.com/view/Executor/job/qe-squid-test-executor-openstack/36/console 

ALL tests are passing.

2024-09-13 11:44 UTC, vamahaja approved these changes

2024-09-13 11:45 UTC, merged