[Test] Validate the /mon endpoint of RESTful module
red-hat-storage/cephci pull request #4084
Opened 2024-09-11 09:17 UTC by sayaleeraut

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2024-09-13 11:48 UTC, vamahaja requested changes

2024-09-13 11:48 UTC, vamahaja commented on tests/mgr/test_restful_operations_mon_endpoint.py
> +    if not [username, endpoint, status_code]:
incorrect validation

2024-09-18 11:23 UTC, sayaleeraut commented
Execution logs -
https://ocs3xstage-jenkins-csb-rhgsocs3x.apps.ocp-c1.prod.psi.redhat.com/view/Executor/job/qe-squid-test-executor-openstack/48/console 

All tests are passing.

2024-09-24 05:59 UTC, vamahaja approved these changes

2024-09-24 05:59 UTC, merged