[Test] Test disconnected upgrade from RHCS 7.x to RHCS 8
red-hat-storage/cephci pull request #4205
Opened 2024-11-06 10:10 UTC by sayaleeraut

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2024-11-07 09:15 UTC, MohitBis commented
@sayaleeraut 

Can you please add passing logs?

2024-11-12 07:49 UTC, vamahaja requested changes

2024-11-12 07:49 UTC, vamahaja commented on tests/ceph_installer/test_disconnected_upgrade.py
> +        cmd = f"podman login {private_registry_url} -u {PRIVATE_REG_USER} -p {PRIVATE_REG_PASS} --tls-verify=False"
Use - https://github.com/red-hat-storage/cephci/blob/master/cli/utilities/containers.py#L9

2024-11-12 08:31 UTC, sayaleeraut commented on tests/ceph_installer/test_disconnected_upgrade.py
> +        cmd = f"podman login {private_registry_url} -u {PRIVATE_REG_USER} -p {PRIVATE_REG_PASS} --tls-verify=False"
done, please review @vamahaja

2024-11-12 10:44 UTC, sayaleeraut commented
Test execution logs -http://magna002.ceph.redhat.com/ceph/cephci-jenkins/saraut/PR_4205/ 

Please note, since RHCS8 repo and container images are not live yet, I manually added the 2 and rest part of upgrade was done by automation script itself.

2024-11-12 10:48 UTC, MohitBis approved these changes
LGTM

2024-11-12 11:24 UTC, merged