This PR adds data and metadata ops after upgrading secondary zone
red-hat-storage/cephci pull request #4237
Opened 2024-11-20 13:17 UTC by viduship

This is to add data and metadata ops after upgrading the secondary zone first

bug [2327402](https://bugzilla.redhat.com/show_bug.cgi?id=2327402)

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-BWPZ5K

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2024-11-20 13:19 UTC, mkasturi18 requested changes

2024-11-20 13:19 UTC, mkasturi18 commented on suites/squid/rgw/tier-1_rgw_ms_upgrade_61GA_to_8x_latest.yaml
> +        cephi-sec:
please fix typo

2024-11-20 13:23 UTC, viduship commented on suites/squid/rgw/tier-1_rgw_ms_upgrade_61GA_to_8x_latest.yaml
> +        cephi-sec:
done.

2024-11-21 04:50 UTC, anrao19 approved these changes
LGTM

2024-11-22 07:52 UTC, TejasC88 commented
LGTM

2024-11-25 11:19 UTC, mkasturi18 approved these changes

2024-11-25 11:20 UTC, merged