Add operations for automation
red-hat-storage/cephci pull request #4250
Opened 2024-11-25 07:44 UTC by NamrathaRao24

# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs
<details>

<summary>click to expand checklist</summary>

- [ ] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [ ] Implement the test script and perform test runs
- [ ] Submit PR for code review and approve
- [ ] Update Polarion Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test
</details>

2024-12-03 04:40 UTC, pranavprakash20 commented on ceph/UI/helper.py
> +def take_ss(driver, filename: str):
Please give meaningful method name. "capture_screen" or "screenshot" etc

2024-12-03 04:41 UTC, pranavprakash20 commented on ceph/UI/helper.py
> +        driver.save_screenshot(filename)
Add logic on returning the screenshot path. The user should be able to get the file name upon calling this method

2024-12-03 04:41 UTC, pranavprakash20 commented on ceph/UI/helper.py
> +def wait_for_element(driver, element_id: str, timeout: int = 10):
Extend the logic for all element types like class, name, xpath, css selector etc and not just to id.

2024-12-03 04:42 UTC, pranavprakash20 commented on ceph/UI/operations.py
> +            login_button = self.driver.find_element_by_id("login")
Add logic to make it generic. Not always its the id, it can accept all other identifiers.

2024-12-03 04:42 UTC, pranavprakash20 requested changes
Please revisit the changes requested

2024-12-03 04:49 UTC, pranavprakash20 commented
@NamrathaRao24 Please add a more meaningful commit message

2025-01-08 04:36 UTC, pranavprakash20 approved these changes
LGTM

2025-01-08 11:43 UTC, psathyan commented
I am unable to find `selenium` module installed as part of `cephci` requirements. This module is being referenced in the code. Are we missing something?

2025-01-13 08:46 UTC, MohitBis approved these changes
LGTM

2025-01-15 10:24 UTC, NamrathaRao24 commented
PRs under review, and the following points need to be addressed:
- Move the login method to dashboard.py.  
- Introduce additional operations.

2025-04-04 19:04 UTC, closed without merging