Test case automation - CEPH-83594337
red-hat-storage/cephci pull request #4289
Opened 2024-12-09 13:36 UTC by chaitanyadommeti

Added module for test CEPH-83594337
Modified add_image_to_group_and_verify() of group.py to handle namespace 
Added test config for CEPH-83594337 in yaml file

Success log for  CEPH-83594337: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-HN6EMK/Test_group_snapshot,_clone,_rollback_from_pool_namespace_0.log

Success log to check existing tests which utilise the sub  add_image_to_group_and_verify() without 'namespace' dont break:
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-GLA40F/Test_cloning_and_flattening_group_snapshot_0.log

2024-12-12 06:49 UTC, sunilangadi2 requested changes

2024-12-12 06:49 UTC, sunilangadi2 commented on ceph/rbd/workflows/group.py
> +                pool(str): pool nane where group should be created
it should be `name`

2024-12-12 06:49 UTC, sunilangadi2 commented on ceph/rbd/workflows/group.py
> +                pool(str): pool nane where group should be created
same here

2024-12-12 06:49 UTC, sunilangadi2 commented on ceph/rbd/workflows/group.py
> +            f"Image {image} to the group {group} and namespace {namespace} successfully verified"
It should be namespace-based images added successfully to group Is it?

2024-12-12 06:49 UTC, sunilangadi2 commented on suites/squid/rbd/tier-2_rbd_group.yaml
> +      module: test_rbd_group_snapshot_on_pool_namespace
module name is wrong. `.py` is missing

2024-12-12 06:49 UTC, sunilangadi2 commented on tests/rbd/test_rbd_group_snapshot_on_pool_namespace.py
> +            log.info("Executing test on Replication and EC pool")
It should be `Replicated`

2024-12-12 06:49 UTC, sunilangadi2 commented on ceph/rbd/workflows/group.py
> -
why it's removed?

2024-12-12 06:49 UTC, sunilangadi2 commented on tests/rbd/test_rbd_group_snapshot_on_pool_namespace.py
> +        Test to verify Cloning and Flattening a Group Snapshot
please correct the method description.

2024-12-12 06:49 UTC, sunilangadi2 commented on tests/rbd/test_rbd_group_snapshot_on_pool_namespace.py
> +            namespace = "ns_" + random_string(len=5)
keep `ns` more descriptive as `namespace`

2024-12-12 06:49 UTC, sunilangadi2 commented on tests/rbd/test_rbd_group_snapshot_on_pool_namespace.py
> +            # dev_path = rbd.map(**{"image-or-snap-spec":f"{pool}/{namespace}/{images[0]}"})
why it's commented?

2024-12-12 06:49 UTC, sunilangadi2 commented on tests/rbd/test_rbd_group_snapshot_on_pool_namespace.py
> +            bench_kw = {
if possbile can we take this IO pattern from test config.

2024-12-12 06:49 UTC, sunilangadi2 commented on tests/rbd/test_rbd_group_snapshot_on_pool_namespace.py
> +            # 4. Create a group and add the image to an RBD group
why number 4 in this comment?

2024-12-12 10:30 UTC, sunilangadi2 reviewed
other changes looks good.

2024-12-12 10:30 UTC, sunilangadi2 commented on ceph/rbd/workflows/group.py
> +        return 0
keep this `return 0` only at the end not needed for each if.

2024-12-12 10:46 UTC, sunilangadi2 commented
EC related data pool not getting deleted here
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-IOZ0KY/Test_group_snapshot,_clone,_rollback_from_pool_namespace_0.log
please add cleanup part similar to this 
https://github.com/red-hat-storage/cephci/pull/4251/files#

2024-12-12 16:05 UTC, chaitanyadommeti commented
> EC related data pool not getting deleted here http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-IOZ0KY/Test_group_snapshot,_clone,_rollback_from_pool_namespace_0.log please add cleanup part similar to this https://github.com/red-hat-storage/cephci/pull/4251/files#

Updated script to avoid 'data_pool' key deletion which is resulting in data pool not getting deleted. 
Success log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-30U1KM/

2024-12-16 06:16 UTC, sunilangadi2 requested changes
@chaitanyadommeti please squash all 20 commits to one commit to merge.

2024-12-17 07:23 UTC, aarsharm approved these changes

2024-12-17 07:55 UTC, closed without merging